2021-01-07 05:32:31,652Z INFO server.py:183 GENESIS START
2021-01-07 05:32:31,652Z INFO server.py:188 Factory config file is found
2021-01-07 05:32:31,653Z INFO heartbeat.py:226 [genesis_health] Nusights metric table is registered
2021-01-07 05:32:31,653Z INFO heartbeat.py:198 [genesis_health] Sending heartbeat to PulseHD every 7 secs
2021-01-07 05:32:31,653Z INFO server.py:199 Starting the serve_http thread
2021-01-07 05:32:31,703Z WARNING lcm_server.py:77 Not starting protobuf RPC server - interface does not support protobuf RPCs
2021-01-07 05:32:31,703Z INFO lifecycle_manager.py:52 interface version: 4.7
2021-01-07 05:32:31,703Z INFO interfaces.py:44 Starting NodeManager
2021-01-07 05:32:31,704Z INFO node_manager.py:371 auxiliary_config: None
2021-01-07 05:32:31,704Z INFO layout_updates.py:483 Inspecting hardware layout file for updates.
2021-01-07 05:32:31,705Z INFO node_manager.py:1620 Assigning IP address 192.168.5.2 to eth1
2021-01-07 05:32:31,782Z ERROR sudo.py:25 Failed to load file /var/run/dhclient-eth1.pid, ret 1, stdout , stderr cat: /var/run/dhclient-eth1.pid: No such file or directory
2021-01-07 05:32:32,849Z INFO node_manager.py:1620 Assigning IP address 192.168.5.254 to eth1:1
2021-01-07 05:32:32,928Z ERROR sudo.py:25 Failed to load file /var/run/dhclient-eth1:1.pid, ret 1, stdout , stderr cat: /var/run/dhclient-eth1:1.pid: No such file or directory
2021-01-07 05:32:35,185Z INFO kvm_upgrade_helper.py:460 Found release marker: el7.nutanix.20190916.253
2021-01-07 05:32:35,185Z INFO kvm_upgrade_helper.py:174 Current hypervisor version: el7.nutanix.20190916.253
2021-01-07 05:32:35,185Z INFO node_manager.py:1972 Certificates directories /home/nutanix/certs or /home/nutanix/certs/CA_certs doesn't exist
2021-01-07 05:32:35,267Z INFO ipv4config.py:964 Netmask is 255.255.252.0
2021-01-07 05:32:35,292Z INFO ipv4config.py:998 Discovered network information: hwaddr 50:6b:8d:9f:80:31, address 10.136.106.162, netmask 255.255.252.0, gateway 10.136.104.1, vlan None
2021-01-07 05:32:35,293Z INFO node_manager.py:5638 Svm has configured ip 10.136.106.162 and device eth0 has ip 10.136.106.162
2021-01-07 05:32:35,293Z INFO node_manager.py:7648 No cached Zeus configuration found.
2021-01-07 05:32:35,307Z INFO ipv4config.py:964 Netmask is 255.255.252.0
2021-01-07 05:32:35,331Z INFO ipv4config.py:998 Discovered network information: hwaddr 50:6b:8d:9f:80:31, address 10.136.106.162, netmask 255.255.252.0, gateway 10.136.104.1, vlan None
2021-01-07 05:32:35,347Z INFO ipv4config.py:721 Only IPv4 is configured for SVM
2021-01-07 05:32:35,361Z WARNING node_manager.py:7597 /home/nutanix/data/zookeeper_monitor/zk_server_config_file could not be opened
2021-01-07 05:32:36,557Z INFO ipv4config.py:721 Only IPv4 is configured for KVM
2021-01-07 05:32:36,557Z ERROR node_manager.py:6076 Zookeeper mapping is unconfigured
2021-01-07 05:32:37,059Z INFO ipv4config.py:1548 IPMI configuration: channel 1 addr 10.136.104.162 mask 255.255.252.0 gw 10.136.104.1
2021-01-07 05:32:45,988Z INFO kvm_utils.py:140 Interface with mac address 50:6b:8d:9f:80:31 does not have vlan id
2021-01-07 05:32:46,002Z WARNING node_manager.py:5795 Unable to discover node identity using IPMI
2021-01-07 05:32:46,002Z INFO node_manager.py:5800 Current svm ip: 10.136.106.162
2021-01-07 05:32:46,003Z INFO node_manager.py:5801 Current zookeeper mapping: {}
2021-01-07 05:32:46,003Z INFO node_manager.py:5803 Current zookeeper config version: None
2021-01-07 05:32:46,459Z INFO kvm_utils.py:140 Interface with mac address 50:6b:8d:9f:80:31 does not have vlan id
2021-01-07 05:32:46,895Z INFO hypervisor_utils.py:425 Successfully read secure boot state of the hypervisor on node 10.136.106.162: Hypervisor is:
2021-01-07 05:32:46,896Z ERROR hypervisor_utils.py:429 Failed to read secure boot state of the hypervisor on nodeCVM IP: 10.136.106.162, Hypervisor IP: 192.168.5.1 using cmd: mokutil --sb-state, err EFI variables are not supported on this system
2021-01-07 05:32:46,897Z WARNING genesis_utils.py:160 Deprecated: use util.cluster.info.get_factory_config() instead
2021-01-07 05:32:46,897Z ERROR certificate_utils.py:160 Invalid FQDN entry
2021-01-07 05:32:47,897Z ERROR genesis_utils.py:160 Service AcropolisHypervisor unable to make certificate request
2021-01-07 05:32:48,897Z ERROR acropolis_service.py:180 Unable to create AHV host certificates
2021-01-07 05:32:48,080Z INFO kvm_upgrade_helper.py:460 Found release marker: el7.nutanix.20190916.253
2021-01-07 05:32:48,080Z INFO kvm_upgrade_helper.py:174 Current hypervisor version: el7.nutanix.20190916.253
2021-01-07 05:32:48,081Z INFO zookeeper_service.py:197 Zookeeper ensemble from node service is, []
2021-01-07 05:32:48,082Z INFO zookeeper_service.py:198 Last known zookeeper ensemble is, {}
2021-01-07 05:32:48,082Z INFO node_manager.py:4048 No cached Zeus configuration found
2021-01-07 05:32:48,082Z ERROR node_manager.py:4059 cluster_function_list is None but we expected exactly 1function
2021-01-07 05:32:48,086Z INFO interfaces.py:39 Starting ClusterManager
2021-01-07 05:32:48,142Z INFO disk_service.py:974 Hades service is available
2021-01-07 05:32:48,142Z INFO disk_service.py:879 Current version: 5.18, multi-disk oplog support enabled: True
2021-01-07 05:32:48,174Z INFO interfaces.py:49 Starting SnapshotManager
2021-01-07 05:32:48,175Z INFO interfaces.py:54 Starting ProtoRPCManager
2021-01-07 05:32:48,176Z INFO zookeeper_service.py:559 Zookeeper mapping not configured, cannot create a zk session.
2021-01-07 05:32:48,176Z INFO igw_interface.py:38 IGW Facade initialized at version {'node_manager': 1, 'cluster_manager': 1}
2021-01-07 05:32:48,761Z INFO interfaces.py:34 Starting GenesisRpcService
2021-01-07 05:32:48,761Z ERROR node_manager.py:6076 Zookeeper mapping is unconfigured
2021-01-07 05:32:49,455Z INFO common_utils.py:710 iptables restarted, sleeping for 2 seconds for iptables init
2021-01-07 05:32:51,749Z INFO common_utils.py:710 ip6tables restarted, sleeping for 2 seconds for ip6tables init
2021-01-07 05:32:53,751Z INFO common_utils.py:712 Restored iptables/ip6tables from backup
2021-01-07 05:32:53,809Z INFO ipv4config.py:964 Netmask is 255.255.252.0
2021-01-07 05:32:53,836Z INFO ipv4config.py:998 Discovered network information: hwaddr 50:6b:8d:9f:80:31, address 10.136.106.162, netmask 255.255.252.0, gateway 10.136.104.1, vlan None
2021-01-07 05:32:53,851Z WARNING genesis_utils.py:233 Interface eth0 is not configured with IPv6
2021-01-07 05:32:54,047Z INFO common_utils.py:746 Not using restricted IPv6 firewall as the support is absent
2021-01-07 05:32:54,048Z INFO common_utils.py:633 Ignoring IPv6 rule -A OUTPUT -s fe80::/10 -j ACCEPT with protocol None
2021-01-07 05:32:54,162Z INFO ipv4config.py:964 Netmask is 255.255.252.0
2021-01-07 05:32:54,192Z INFO ipv4config.py:998 Discovered network information: hwaddr 50:6b:8d:9f:80:31, address 10.136.106.162, netmask 255.255.252.0, gateway 10.136.104.1, vlan None
2021-01-07 05:32:54,287Z INFO legacy.py:170 Rule added: sudo_wrapper iptables -A CLUSTERLIST -s 10.136.106.162/255.255.252.0 -j ACCEPT
2021-01-07 05:32:54,381Z INFO legacy.py:170 Rule added: sudo_wrapper iptables -A CLUSTERLIST -s 192.168.5.255/255.255.255.0 -j ACCEPT
2021-01-07 05:32:54,502Z INFO node_manager.py:3964 Starting vlan_sniffer with command: /home/nutanix/cluster/bin/vlan_sniffer_proxy --sniffer_args='-n -i br0 ip6 multicast and ip6 proto 17 and port 13000'
2021-01-07 05:32:54,508Z INFO node_manager.py:1854 Upgrade check.
2021-01-07 05:32:54,515Z INFO zookeeper_service.py:559 Zookeeper mapping not configured, cannot create a zk session.
2021-01-07 05:32:54,515Z WARNING cluster_manager.py:3271 No Zeus session available
2021-01-07 05:32:54,516Z ERROR node_manager.py:1864 Could not get release version
2021-01-07 05:32:54,516Z INFO service_utils.py:656 Starting foundation with rlimits {5: 167772160}
2021-01-07 05:32:54,516Z INFO service_utils.py:690 Starting foundation with cmd  /home/nutanix/foundation/bin/foundation --foreground |& /home/nutanix/bin/logpipe -o /home/nutanix/data/logs/foundation.out
2021-01-07 05:32:54,520Z INFO service_utils.py:445 Delete current hub's threadpool.
2021-01-07 05:32:54,520Z INFO service_utils.py:449 Destroy hub and default loop.
2021-01-07 05:32:54,523Z INFO service_utils.py:445 Delete current hub's threadpool.
2021-01-07 05:32:54,524Z INFO service_utils.py:449 Destroy hub and default loop.
2021-01-07 05:32:54,524Z INFO service_utils.py:305 Creating cgroup foundation.
2021-01-07 05:32:54,594Z INFO ipv4config.py:964 Netmask is 255.255.252.0
2021-01-07 05:32:54,629Z INFO ipv4config.py:998 Discovered network information: hwaddr 50:6b:8d:9f:80:31, address 10.136.106.162, netmask 255.255.252.0, gateway 10.136.104.1, vlan None
2021-01-07 05:32:54,631Z INFO service_utils.py:317 Setting memory limit for cgroup foundation to 167772160.
2021-01-07 05:32:54,714Z INFO service_utils.py:360 Adding process id 3346 to cgroup foundation.
2021-01-07 05:32:54,821Z INFO service_utils.py:390 Setting oom score 100 for foundation with process id 3346.
2021-01-07 05:32:54,826Z INFO zookeeper_service.py:559 Zookeeper mapping not configured, cannot create a zk session.
2021-01-07 05:32:55,304Z INFO helper.py:184 use_salt_based_firewall returned False, reason: cached proto/zk mapping do not exist, assuming unconfigured node
2021-01-07 05:32:55,304Z INFO helper.py:212 Using legacy firewall framework
2021-01-07 05:32:55,324Z INFO ipv4config.py:964 Netmask is 255.255.252.0
2021-01-07 05:32:55,358Z INFO ipv4config.py:998 Discovered network information: hwaddr 50:6b:8d:9f:80:31, address 10.136.106.162, netmask 255.255.252.0, gateway 10.136.104.1, vlan None
2021-01-07 05:32:55,380Z WARNING genesis_utils.py:233 Interface eth0 is not configured with IPv6
2021-01-07 05:32:55,605Z INFO common_utils.py:746 Not using restricted IPv6 firewall as the support is absent
2021-01-07 05:32:55,606Z INFO common_utils.py:633 Ignoring IPv6 rule -A OUTPUT -s fe80::/10 -j ACCEPT with protocol None
2021-01-07 05:32:55,606Z WARNING node_manager.py:841 Cached proto is not available, skipping IPv6 parameter
2021-01-07 05:32:55,607Z INFO common_utils.py:746 Not using restricted IPv6 firewall as the support is absent
2021-01-07 05:32:55,607Z INFO legacy.py:192 Executing sudo_wrapper iptables -C WORLDLIST -p tcp -m tcp --dport 8000 -j ACCEPT
2021-01-07 05:32:55,721Z INFO legacy.py:201 Executing sudo_wrapper iptables -A WORLDLIST -p tcp -m tcp --dport 8000 -j ACCEPT
2021-01-07 05:32:55,841Z INFO legacy.py:192 Executing sudo_wrapper ip6tables -C INPUT -p tcp -m tcp --dport 8000 -j ACCEPT
2021-01-07 05:32:55,956Z INFO legacy.py:201 Executing sudo_wrapper ip6tables -A INPUT -p tcp -m tcp --dport 8000 -j ACCEPT
2021-01-07 05:32:56,296Z INFO zookeeper_session.py:176 genesis is attempting to connect to Zookeeper
2021-01-07 05:33:16,297Z ERROR genesis_utils.py:2566 Could not reach zookeeper
2021-01-07 05:33:16,299Z ERROR genesis_utils.py:311 Failed to get CVM id
2021-01-07 05:33:16,300Z INFO node_manager.py:6114 Waiting for node to become configured through RPC
2021-01-07 05:33:16,300Z ERROR node_manager.py:6076 Zookeeper mapping is unconfigured
2021-01-07 05:33:36,248Z ERROR node_manager.py:6076 Zookeeper mapping is unconfigured
2021-01-07 05:33:36,252Z ERROR node_manager.py:6076 Zookeeper mapping is unconfigured
2021-01-07 05:34:30,207Z ERROR node_manager.py:6076 Zookeeper mapping is unconfigured
2021-01-07 05:32:44,166Z INFO node_manager.py:8028 Configuring the hypervisor with DNS servers [u'10.136.100.10']
2021-01-07 05:32:44,612Z INFO node_manager.py:8040 No DNS configuration change on the hypervisor required
2021-01-07 05:32:50,175Z INFO kvm_utils.py:140 Interface with mac address 50:6b:8d:9f:80:31 does not have vlan id
2021-01-07 05:32:50,612Z INFO hypervisor_utils.py:425 Successfully read secure boot state of the hypervisor on node 10.136.106.162: Hypervisor is:
2021-01-07 05:32:50,612Z ERROR hypervisor_utils.py:429 Failed to read secure boot state of the hypervisor on nodeCVM IP: 10.136.106.162, Hypervisor IP: 192.168.5.1 using cmd: mokutil --sb-state, err EFI variables are not supported on this system
2021-01-07 05:32:56,590Z INFO common_utils.py:746 Not using restricted IPv6 firewall as the support is absent
2021-01-07 05:32:56,608Z INFO ipv4config.py:964 Netmask is 255.255.252.0
2021-01-07 05:32:56,637Z INFO ipv4config.py:998 Discovered network information: hwaddr 50:6b:8d:9f:80:31, address 10.136.106.162, netmask 255.255.252.0, gateway 10.136.104.1, vlan None
2021-01-07 05:32:56,910Z INFO salt.py:287 Executing salt call for CVM
2021-01-07 05:32:59,870Z INFO salt.py:296 Successfully executed salt command
2021-01-07 05:32:59,871Z INFO node_manager.py:5512 iptables rules applied for state kBaseConfig
2021-01-07 05:33:12,514Z ERROR node_manager.py:6076 Zookeeper mapping is unconfigured
2021-01-07 05:33:12,555Z INFO node_manager.py:6861 Updating /etc/hosts
2021-01-07 05:33:12,555Z INFO node_manager.py:6864 Configuring the node with zookeeper ensemble: {u'10.136.106.161': 2, u'10.136.106.163': 1, u'10.136.106.164': 3}
2021-01-07 05:33:12,807Z WARNING node_manager.py:7597 /home/nutanix/data/zookeeper_monitor/zk_server_config_file could not be opened
2021-01-07 05:33:12,808Z INFO node_manager.py:6988 Local zk config version: None
2021-01-07 05:33:12,808Z INFO node_manager.py:4048 No cached Zeus configuration found
2021-01-07 05:33:12,826Z INFO node_manager.py:6122 Woke up; checking if node is configured
2021-01-07 05:33:12,826Z INFO zookeeper_session.py:176 genesis is attempting to connect to Zookeeper
2021-01-07 05:33:13,472Z INFO zookeeper_service.py:284 Environment variables are modified; current shell may need to be updated
2021-01-07 05:33:32,941Z ERROR genesis_utils.py:2566 Could not reach zookeeper
2021-01-07 05:33:32,942Z ERROR genesis_utils.py:311 Failed to get CVM id
2021-01-07 05:33:32,942Z ERROR genesis_utils.py:2443 Valid zookeeper session not provided
2021-01-07 05:33:32,942Z ERROR genesis_utils.py:2129 Invalid zk session
2021-01-07 05:33:32,942Z INFO node_manager.py:6088 Stopping Foundation service
2021-01-07 05:33:32,949Z INFO zookeeper_session.py:176 genesis is attempting to connect to Zookeeper
2021-01-07 05:33:53,026Z ERROR genesis_utils.py:2566 Could not reach zookeeper
2021-01-07 05:33:53,026Z ERROR genesis_utils.py:311 Failed to get CVM id
2021-01-07 05:33:53,027Z INFO foundation_rest_client.py:130 Making GET request to http://localhost:8000/foundation/get_progress_sessions
2021-01-07 05:33:53,028Z INFO node_manager.py:3979 Killing vlan sniffer process
2021-01-07 05:33:53,039Z INFO foundation_service.py:182 Stopping foundation service
2021-01-07 05:33:53,129Z INFO node_manager.py:3999 Removing tagged interfaces []
2021-01-07 05:33:53,207Z WARNING node_manager.py:4017 Route change failed: 0
2021-01-07 05:33:53,213Z INFO node_manager.py:2700 Starting NodeManager
2021-01-07 05:33:53,213Z INFO node_manager.py:1620 Assigning IP address 192.168.5.2 to eth1
2021-01-07 05:33:53,289Z ERROR sudo.py:25 Failed to load file /var/run/dhclient-eth1.pid, ret 1, stdout , stderr cat: /var/run/dhclient-eth1.pid: No such file or directory
2021-01-07 05:33:53,308Z INFO service_utils.py:912 No process has lock_path /home/nutanix/data/locks/foundation open
2021-01-07 05:33:53,379Z INFO ipv4config.py:964 Netmask is 255.255.252.0
2021-01-07 05:33:53,429Z INFO ipv4config.py:998 Discovered network information: hwaddr 50:6b:8d:9f:80:31, address 10.136.106.162, netmask 255.255.252.0, gateway 10.136.104.1, vlan None
2021-01-07 05:33:53,572Z INFO zookeeper_service.py:566 Creating ZookeeperSession for the first time